- id: "1755384623909"
  alias: Maestro Send State Changed
  description: ""
  triggers:
    - trigger: event
      event_type: state_changed
      context: {}
  conditions:
    - condition: not
      conditions:
        - condition: template
          value_template:
            "{{ trigger.event.data.entity_id.startswith('automation.')
            }}"
  actions:
    - action: rest_command.maestro_send_state_change
      metadata: {}
      data:
        time_fired: "{{ trigger.event.time_fired }}"
        event_type: "{{ trigger.event.event_type }}"
        entity_id: "{{ trigger.event.data.entity_id }}"
        old_state:
          "{{ trigger.event.data.old_state.state if trigger.event.data.old_state
          else none }}"
        new_state:
          "{{ trigger.event.data.new_state.state if trigger.event.data.new_state
          else none }}"
        old_attributes:
          "{{ trigger.event.data.old_state.attributes | tojson if trigger.event.data.old_state
          else none }}"
        new_attributes:
          "{{ trigger.event.data.new_state.attributes | tojson if trigger.event.data.new_state
          else none }}"
  mode: parallel
- id: "1758549424655"
  alias: Maestro Send Event Fired
  description: ""
  triggers:
    - trigger: event
      event_type: "*"
      context: {}
  conditions:
    - condition: not
      conditions:
        - condition: template
          value_template:
            '{{ trigger.event.event_type in ["state_changed", "automation_triggered",
            "call_service", "pyscript_running"] }}'
  actions:
    - action: rest_command.maestro_send_event
      metadata: {}
      data:
        time_fired: "{{ trigger.event.time_fired }}"
        event_type: "{{ trigger.event.event_type }}"
        user_id: "{{ trigger.event.context.user_id }}"
        data: "{{ trigger.event.data | tojson }}"
  mode: parallel
