automation: !include automations.yaml

default_config:

frontend:
  themes: !include themes/themes.yaml
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
      allow_bypass_login: true
    - type: homeassistant

logger:
  default: warn
  logs:
    custom_components.tesla_custom: fatal
    homeassistant.core: fatal
    homeassistant.components.input_select: fatal
    homeassistant.components.led_ble: fatal
    led_ble.led_ble: fatal
    pychromecast.controllers: fatal
    pychromecast.socket_client: fatal
    somecomfort: fatal

lovelace:
  mode: storage
  dashboards:
    lovelace-cast:
      mode: yaml
      title: Cast
      icon: mdi:cast
      show_in_sidebar: true
      filename: ui-cast.yaml
    lovelace-mobile:
      mode: yaml
      title: Mobile
      icon: mdi:cellphone
      show_in_sidebar: true
      filename: ui-mobile.yaml

panel_custom: !include panel_custom.yaml

pyscript: !include pyscript/config.yaml

scene: !include scenes.yaml

script: !include scripts.yaml

rest_command:
  send_to_maestro:
    url: !secret maestro_state_changed_url
    method: POST
    headers:
      Content-Type: "application/json"
      X-Auth-Token: !secret maestro_token
    payload: >
      {
        "event_type": {{ event_type | tojson }},
        "event_data": {{ event_data | tojson }},
        "time_fired": {{ time_fired | tojson }},
        "timestamp": {{ now().isoformat()| tojson }}
      }

shell_command:
  cast_to_office_display: python3 -m pip install catt && catt -d 'Office Display' cast_site 'http://192.168.0.107:8123/lovelace-cast/overview'
  cast_to_living_room_display: python3 -m pip install catt && catt -d 'Living Room Display' cast_site 'http://192.168.0.107:8123/lovelace-cast/overview'
  cast_to_kitchen_display: python3 -m pip install catt && catt -d 'Kitchen Display' cast_site 'http://192.168.0.107:8123/lovelace-cast/overview'

tts:
  - platform: google_translate

########################################

command_line:
  - sensor:
      name: CPU Temperature
      command: "cat /sys/class/thermal/thermal_zone0/temp"
      value_template: "{{ value | multiply(0.0018) | round(0) + 32 }}"

cover:
  - platform: template
    covers:
      east_stall:
        device_class: garage
        friendly_name: "East Stall"
        value_template: "{{ is_state('binary_sensor.east_stall_input', 'off') }}"
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.east_stall
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.east_stall
  - platform: template
    covers:
      west_stall:
        device_class: garage
        friendly_name: "West Stall"
        value_template: "{{ is_state('binary_sensor.west_stall_input', 'off') }}"
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.west_stall
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.west_stall

sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time_iso"
