kiosk_mode: !include lovelace/cast-kiosk-mode.yaml
sidebar: !include lovelace/cast-sidebar.yaml
views:
  - theme: Backend-selected
    title: Overview
    type: panel
    icon: mdi:view-dashboard
    path: overview
    badges: []
    cards:
      - type: custom:mod-card
        style: !include lovelace/style-cast-view.yaml
        card:
          type: horizontal-stack
          cards:
            - type: vertical-stack
              cards:
                - !include lovelace/overview/weather.yaml
                - !include lovelace/overview/garage-buttons.yaml
                - !include lovelace/overview/chelsea-fixture.yaml
                - !include lovelace/overview/entity-row-1.yaml
            - type: vertical-stack
              cards:
                - !include lovelace/overview/people-simple.yaml
                - !include lovelace/overview/media.yaml
                - !include lovelace/overview/entity-row-2.yaml
  - theme: Backend-selected
    title: Family
    type: panel
    icon: mdi:human-male-female-child
    path: family
    badges: []
    cards:
      - type: custom:mod-card
        style: !include lovelace/style-cast-view.yaml
        card:
          type: horizontal-stack
          cards:
            - type: vertical-stack
              cards:
                - !include lovelace/family/people-detailed.yaml
                - !include lovelace/family/map.yaml
            - type: vertical-stack
              cards:
                - !include lovelace/family/calendar-family.yaml
  - theme: Backend-selected
    title: Home
    type: panel
    icon: mdi:home
    path: home
    badges: []
    cards:
      - type: custom:mod-card
        style: !include lovelace/style-cast-view.yaml
        card:
          type: horizontal-stack
          cards:
            - type: vertical-stack
              cards:
                - !include lovelace/home/devices.yaml
            - type: vertical-stack
              cards:
                - !include lovelace/home/thermostat.yaml
  - theme: Backend-selected
    title: Soccer
    type: panel
    icon: mdi:soccer
    path: soccer
    badges: []
    cards:
      - type: custom:mod-card
        style: !include lovelace/style-cast-view.yaml
        card:
          type: horizontal-stack
          cards:
            - type: vertical-stack
              cards:
                - !include lovelace/soccer/calendar-fixtures.yaml
            - type: vertical-stack
              cards: 
                - !include lovelace/soccer/league-tabs.yaml
                - !include lovelace/soccer/league-data.yaml
  - theme: Backend-selected
    title: System
    type: panel
    icon: mdi:tools
    path: system 
    badges: []
    cards:
      - type: custom:mod-card
        style: !include lovelace/style-cast-view.yaml
        card:
          type: horizontal-stack
          cards:
            - type: vertical-stack
              cards:
                - !include lovelace/system/admin-entities.yaml
            - type: vertical-stack
              cards:
                - !include lovelace/system/updates.yaml