views:
  - theme: Backend-selected
    title: Overview
    type: panel
    icon: mdi:view-dashboard
    path: overview
    badges: []
    cards:
      - type: custom:mod-card
        style: !include lovelace/style-mobile-view.yaml
        card:
          type: vertical-stack
          cards:
            - !include lovelace/overview/people-simple.yaml
            - !include lovelace/overview/garage-buttons.yaml
            - !include lovelace/overview/media.yaml
            - type: horizontal-stack
              cards:
                - !include lovelace/entity-cards/card-1.yaml
                - !include lovelace/entity-cards/card-2.yaml
                - !include lovelace/entity-cards/card-3.yaml
            - type: horizontal-stack
              cards:
                - !include lovelace/entity-cards/card-4.yaml
                - !include lovelace/entity-cards/card-5.yaml
                - !include lovelace/entity-cards/card-6.yaml
  - theme: Backend-selected
    title: Family
    type: panel
    icon: mdi:human-male-female-child
    path: family
    badges: []
    cards:
      - type: custom:mod-card
        style: !include lovelace/style-mobile-view.yaml
        card:
          type: vertical-stack
          cards:
            - !include lovelace/family/people-detailed.yaml
            - !include lovelace/family/map.yaml
  - theme: Backend-selected
    title: Home
    type: panel
    icon: mdi:home
    path: home
    badges: []
    cards:
      - type: custom:mod-card
        style: !include lovelace/style-mobile-view.yaml
        card:
          type: vertical-stack
          cards:
            - !include lovelace/home/climate.yaml
            - !include lovelace/home/devices.yaml
  - theme: Backend-selected
    title: Thinker
    type: panel
    icon: mdi:head-dots-horizontal
    path: thinker
    badges: []
    cards:
      - type: custom:mod-card
        style: !include lovelace/style-mobile-view.yaml
        card:
          type: vertical-stack
          cards:
            - !include lovelace/thinker/review-thoughts.yaml
            - !include lovelace/thinker/review-actions.yaml
            - !include lovelace/thinker/review-edit.yaml
  - theme: Backend-selected
    title: Soccer
    type: panel
    icon: mdi:soccer
    path: soccer
    badges: []
    cards:
      - type: custom:mod-card
        style: !include lovelace/style-mobile-view.yaml
        card:
          type: vertical-stack
          cards:
            - !include lovelace/soccer/league-tabs.yaml
            - !include lovelace/soccer/league-data.yaml
  - theme: Backend-selected
    title: System
    type: panel
    icon: mdi:tools
    path: system
    badges: []
    cards:
      - type: custom:mod-card
        style: !include lovelace/style-mobile-view.yaml
        card:
          type: vertical-stack
          cards:
            - !include lovelace/system/preferences.yaml
            - !include lovelace/system/admin-buttons.yaml
            - !include lovelace/system/updates.yaml
            - !include lovelace/system/status.yaml
