global:
  sidebar-background: "#2A2A2A"
  custom-card-active-background-color: "#777"
  custom-warning-background-color: "#F00"
  custom-warning-text-color: "#F00"
  custom-favorable-text-color: "#0F0"
  mdc-select-fill-color: none

themes:
  Default:
    background: homekit-bg-blue-red.jpg
  Red, White, & Blue:
    background: red-white-blue.jpg
    custom-primary-accent: "#D00"
    custom-switch-checked: "#00D"
    primary-color: var(--custom-primary-accent)
    accent-color: var(--custom-primary-accent)
    switch-checked-color: var(--custom-switch-checked)
    switch-checked-track-color: var(--custom-switch-checked)
  Springtime:
    background: cherry-blossoms.jpg
    custom-primary-accent: rgb(230, 160, 190)
    custom-switch-checked: rgb(110, 170, 240)
    primary-color: var(--custom-primary-accent)
    accent-color: var(--custom-primary-accent)
    switch-checked-color: var(--custom-switch-checked)
    switch-checked-track-color: var(--custom-switch-checked)
    ha-card-background: rgba(10, 10, 10, 0.55)
    custom-card-active-background-color: "#7B7B7B"
  Halloween:
    background: spooky-cemetary.jpg
    custom-primary-accent: rgb(240, 130, 70)
    custom-switch-checked: rgb(50, 100, 60)
    primary-color: var(--custom-primary-accent)
    accent-color: var(--custom-primary-accent)
    switch-checked-color: var(--custom-switch-checked)
    switch-checked-track-color: var(--custom-switch-checked)
